# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jy54C2Rtp8omW8Ui7w_GQdwZi5LxaCNm
"""

import pandas as pd
import numpy as np

#misogynistic keyword dataset
keyword_df = pd.read_csv('/content/keyword_df.csv')
#the dataset includes previous predicted label which failed to identify feminist texts, so the predicted lebla and confidence will be removed
keyword_df = keyword_df.drop(['predicted_label', 'confidence'], axis=1)
keyword_df.head()

keyword_df.isna().sum()

keyword_df = keyword_df.dropna()

#hot topics dataset
hot_topics_df = pd.read_csv('/content/topic_df.csv')

hot_topics_df.head()

hot_topics_df.isna().sum()

hot_topics_df = hot_topics_df.dropna()

##SWSR dataset
comments = pd.read_csv('/content/SWSR_SexComment.csv')
posts = pd.read_csv('/content/SWSR_SexWeibo.csv')

comments.head()

posts.head()

"""The SWSR (Sex Comments and Sex Posts) dataset is actually really similar to the keyword dataset that I acquired myself it seems."""

posts['weibo_date'] = posts['weibo_date'].astype('datetime64[ns]')
posts['weibo_date'].max()-posts['weibo_date'].min()

#just wanted to make sure if the keyword dataset has a much shorter time range
keyword_df['created_at'] = pd.to_datetime(keyword_df['created_at'])
keyword_df['created_at'].max()-keyword_df['created_at'].min()

print(posts['keyword'].unique())
posts['keyword'].nunique()

print(keyword_df['keyword'].unique())
keyword_df['keyword'].nunique()

"""as the newest journal uses weibo comments instead of posts, let's make sure that the data is clean"""

comments.isna().sum()

comments['label']

comments[comments['label'] == 1].shape[0] / comments.shape[0]

#around 35% are identified as misogynistic in this dataset by the authors